baseURL = "https://ipsy-md.github.io/docs/"
title = "IPSY Docs"
languageCode = "en-us"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html$']

#[params]
#    geekdocMenuBundle = true
#	geekdocOverwriteHTMLBase = true
